language: python
python:
- "3.7.4"
install: pip install -r requirements.txt
script:
- SECRET_KEY="whatever" ./manage.py test
before_install:
  - chmod +x manage.py
before_script:
  - isort --skip migrations --diff 