language: python
python:
- "3.7.4"
install: pip install -r requirements.txt
script:
- isort --check-only --diff --skip-glob=*/migrations/*
- SECRET_KEY="whatever" ./manage.py test
before_install:
  - chmod +x manage.py